version: "3.8"

services:
  client:
    container_name: vue_frontend
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "8080:80"
    volumes:
      - ./client:/app
    depends_on:
      - server

  server:
    container_name: django_backend
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - DATABASE_NAME=manageproducts
      - DATABASE_USER=root
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mysql_db
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: manageproducts
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
